### ISSUE TITLE
Request testnet funds

### ISSUE THREAD

**Issue by XGnar** [cosmos/vega-test#22]
Hello this is my addresses from keplr extention :
cosmos1uvenyjazulhzyd4707k7gracxpfmffa6vmvewf
cosmos1k6a85zhwxnh3zth2zk897zmsgtyt99r580qjsx
cosmos17lgg3gwazagrqkdcyeqcn2jw9f59n4pumd9jjk

**Comment by uditvira** [comment]
sent!
