### ISSUE TITLE
Requesting testnet funds

### ISSUE THREAD

**Issue by PhSteel** [cosmos/vega-test#29]
@uditvira, please send ATOM tokens to dev account : cosmos1mkvf80cxgtjsy2sa7ct6dd895l9r67pause73n

**Comment by PhSteel** [comment]
Pinging again @nooomski @uditvira @okwme.

**Comment by nooomski** [comment]
Done! https://vega-explorer.hypha.coop/transactions/37078764E299C2FC3625B424B9878B2EE320125F5E06E686893D4F06D58D56CB
